# Generated by Django 3.2 on 2022-11-16 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=800)),
                ("alt_img", models.CharField(max_length=800)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=1200)),
                ("description", models.CharField(max_length=800)),
                ("date", models.DateField(default=datetime.date(2022, 11, 16))),
                ("language", models.CharField(max_length=200)),
                ("audience_type", models.CharField(max_length=200)),
                ("reading_time", models.IntegerField(default=1)),
                ("category", models.CharField(max_length=200)),
                ("blog_link", models.CharField(max_length=200)),
                ("recommendation_type", models.CharField(max_length=200)),
            ],
        ),
    ]
