# Generated by Django 3.2 on 2022-11-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="alt_img",
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="audience_type",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="author",
            field=models.CharField(default=None, max_length=1200),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="blog_link",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="category",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="description",
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="img",
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="language",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="recommendation_type",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="blogmodel",
            name="title",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
