# Generated by Django 3.2 on 2022-11-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221116_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_reader',
            field=models.BooleanField(default=False),
        ),
    ]
