# Generated by Django 3.2 on 2022-11-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModel',
        ),
        migrations.DeleteModel(
            name='userPreferenceModel',
        ),
    ]
