# Generated by Django 3.2 on 2022-11-16 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20221116_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 12, 34, 54, 3557, tzinfo=utc)),
        ),
    ]
