# Generated by Django 3.2 on 2022-11-16 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blogmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 12, 35, 20, 785673, tzinfo=utc)),
        ),
    ]
