# Generated by Django 3.2 on 2022-11-16 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_blogmodel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('interests', models.CharField(max_length=200)),
                ('preference', models.CharField(max_length=200)),
                ('user_type', models.CharField(max_length=200)),
                ('is_reader', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 12, 35, 55, 386768, tzinfo=utc)),
        ),
    ]
