# Generated by Django 3.2 on 2022-11-16 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221116_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 16, 13, 54, 50, 242931, tzinfo=utc)),
        ),
    ]
